[package]
name = "tomlparse"
version = "0.2.0"
authors = ["Luke Oliver <galactic.fungus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
